import os
import io
from datetime import datetime
from fpdf import FPDF
from docx import Document
from report_builder import generate_advisor_report
from database import get_advisor_finding_by_id

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'Forensic AI Audit Report', border=0, new_x="LMARGIN", new_y="NEXT", align='C')
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 10, 'Generated by Forensic CPA AI', border=0, new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', border=0, new_x="LMARGIN", new_y="NEXT", align='C')

def generate_pdf_export(report_data: dict) -> bytes:
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Metadata
    pdf.set_font("Helvetica", size=10)
    generated_at = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    company_id = report_data.get('company_id', 'Unknown')
    mode = report_data.get('mode', 'client').title()
    
    pdf.cell(0, 6, f"Company ID: {company_id}", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Report Mode: {mode}-Facing", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Generated At: {generated_at}", border=0, new_x="LMARGIN", new_y="NEXT")
    if 'date_range' in report_data:
        pdf.cell(0, 6, f"Date Range: {report_data['date_range']}", border=0, new_x="LMARGIN", new_y="NEXT")
    if 'analysis_run_id' in report_data:
        pdf.cell(0, 6, f"Run ID: {report_data['analysis_run_id']}", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    def _add_markdown_text(pdf_obj, text: str):
        # Extremely basic markdown to FPDF converter.
        for line in text.split('\n'):
            line = line.strip()
            if not line:
                pdf_obj.ln(4)
                continue
            
            if line.startswith('### '):
                pdf_obj.set_font("Helvetica", 'B', 12)
                pdf_obj.multi_cell(0, 8, line[4:].replace('**', ''))
                pdf_obj.set_font("Helvetica", '', 10)
            elif line.startswith('## '):
                pdf_obj.set_font("Helvetica", 'B', 14)
                pdf_obj.multi_cell(0, 10, line[3:].replace('**', ''))
                pdf_obj.set_font("Helvetica", '', 10)
            else:
                # remove bold markdown since fpdf2 multi_cell handles markdown if we use HTML, but using basic text here
                clean_line = line.replace('**', '')
                pdf_obj.multi_cell(0, 6, clean_line)

    # Executive Summary
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, "Executive Summary", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", '', 10)
    _add_markdown_text(pdf, report_data.get("executive_summary", ""))
    pdf.ln(10)
    
    # Detailed Findings
    for section in report_data.get("detailed_findings", []):
        pdf.add_page()
        pdf.set_font("Helvetica", 'B', 14)
        pdf.cell(0, 10, section.get("category", "Findings"), border=0, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", '', 10)
        _add_markdown_text(pdf, section.get("content", ""))
        
    # Appendix
    pdf.add_page()
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, "Appendix & Transcripts", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", '', 10)
    _add_markdown_text(pdf, report_data.get("appendix", ""))
    
    return bytes(pdf.output())


def generate_docx_export(report_data: dict) -> bytes:
    doc = Document()
    doc.add_heading('Forensic AI Audit Report', 0)
    
    generated_at = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    doc.add_paragraph(f"Company ID: {report_data.get('company_id', 'Unknown')}")
    doc.add_paragraph(f"Report Mode: {report_data.get('mode', 'client').title()}-Facing")
    doc.add_paragraph(f"Generated At: {generated_at}")
    if 'date_range' in report_data:
        doc.add_paragraph(f"Date Range: {report_data['date_range']}")
    if 'analysis_run_id' in report_data:
        doc.add_paragraph(f"Run ID: {report_data['analysis_run_id']}")
        
    def _add_markdown_doc(document, text: str):
        for line in text.split('\n'):
            line = line.strip()
            if not line:
                continue
            if line.startswith('### '):
                document.add_heading(line[4:].replace('**', ''), level=3)
            elif line.startswith('## '):
                document.add_heading(line[3:].replace('**', ''), level=2)
            else:
                p = document.add_paragraph(line.replace('**', ''))
    
    doc.add_heading('Executive Summary', level=1)
    _add_markdown_doc(doc, report_data.get("executive_summary", ""))
    
    for section in report_data.get("detailed_findings", []):
        doc.add_page_break()
        doc.add_heading(section.get("category", "Findings"), level=1)
        _add_markdown_doc(doc, section.get("content", ""))
        
    doc.add_page_break()
    doc.add_heading('Appendix & Transcripts', level=1)
    _add_markdown_doc(doc, report_data.get("appendix", ""))
    
    f = io.BytesIO()
    doc.save(f)
    return f.getvalue()

def build_finding_report(company_id: int, finding_id: str, mode: str = 'client') -> dict:
    f = get_advisor_finding_by_id(company_id, finding_id)
    if not f:
        return {}
    
    # Render into minimal report structure compatible with our doc generators
    ev_graph = f.get('evidence_graph', [])
    ev_str = ", ".join([f"[EVID-{e['type']}-{e['id']}]" for e in ev_graph if 'id' in e])
    
    narratives = []
    if mode == 'client':
        narratives.append(f"### {f['title']}")
        narratives.append(f"**What we found:** {f.get('plain_english_explanation', '')}")
        narratives.append(f"**Why it matters:** {f.get('executive_summary', '')}")
        narratives.append(f"**Evidence:** ({ev_str})")
        impact = f.get('financial_impact', {})
        if impact:
            narratives.append(f"**Financial impact:** {impact.get('amount', 'N/A')}")
        if f.get('recommended_actions'):
            narratives.append(f"**How to fix:** " + " ".join(f['recommended_actions']))
    else:
        narratives.append(f"### {f['title']} (Sev: {f.get('severity', 'none').upper()})")
        narratives.append(f"**Forensic Rationale:** {f.get('forensic_rationale', '')}")
        narratives.append(f"**Traceability (Evidence):** Nodes {ev_str}")
        if f.get('recommended_actions'):
            narratives.append(f"**Control Recommendations:** " + " ".join(f['recommended_actions']))
            
    return {
        "company_id": company_id,
        "mode": mode,
        "analysis_run_id": f.get('analysis_run_id', 'N/A'),
        "executive_summary": "Single Finding Export",
        "detailed_findings": [
            {
                "category": f.get("category", "Unknown").replace("_", " ").title(),
                "content": "\n\n".join(narratives)
            }
        ],
        "appendix": ev_str
    }
